app.py
#!/usr/bin/python3.6
from flask import Flask,url_for


from main.blog_blueprint import blog_print

from main.provider import Article_Notification


#application creation function
def create_application(setup,*blueprint):
    app = Flask(__name__)
    app.config.from_object(setup)
    
    #registering all blueprint to application
    for blues in blueprint:
        app.register_blueprint(blues)
    
    
    return app

app = create_application('config.Development',blog_print)

if __name__ == '__main__':
    
    app.run(port=8081,host='localhost')

main/blog_blueprint.py
from flask import Blueprint

blog_print = Blueprint('blogger',__name__)

from .navigators import errors
from .navigators import views

main/navigators/views.py
from ..blog_blueprint import blog_print
from flask import render_template,abort,g,url_for
from jinja2 import TemplateNotFound
from re import search
from pathlib import Path







@blog_print.route('/')
def homepage():
    
    return render_template('blogger/index.html')


@blog_print.route('/about')
def about():
    return render_template('blogger/about.html')


@blog_print.route('/terms_and_conditions')
def terms_and_conditions():
    return render_template('blogger/terms.html')

@blog_print.route('/favicon.ico')
def banner():
    image = b''
    with open('static/images/favicon.ico','rb') as r_file:
        image = r_file.read()
    return image



@blog_print.route('/programming')
def programming():
    
    return render_template('blogger/Programming/index.html')

@blog_print.route('/chemistry')
def chemistry():
    
    return render_template('blogger/Chemistry/index.html')

@blog_print.route('/biology')
def biology():
    
    return render_template('blogger/Biology/index.html')


#article display
@blog_print.route('/biology/<name>')
def p_article(name):
    try:
        return render_template(f'blogger/Biology/{name}')
    except TemplateNotFound:
        print('here')
        abort(404)
    

@blog_print.route('/programming/<name>')
def c_article(name):
    try:
        return render_template(f'blogger/Programming/{name}')
    except TemplateNotFound:
        abort(404)

@blog_print.route('/chemistry/<name>')
def b_article(name):
    try:
        return render_template(f'blogger/Chemistry/{name}')
    except TemplateNotFound:
        abort(404)

templates/blogger/Biology/index.html
<!DOCTYPE HTML>

<html>
	<head>
		<title>Ioton</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{{url_for('static',filename='assets/css/main.css')}}" />
	</head>
	<body class="subpage">

		<!-- Header -->
			<header id="header">
				<div class="logo"><a href="{{url_for('blogger.homepage')}}">Io<span>Ton</span></a></div>
				<a href="#menu">Menu</a>
			</header>

		<!-- Nav --> 
			<nav id="menu">
				<ul class="links">
					<li><a href="{{url_for('blogger.homepage')}}">Home</a></li>
					<li><a href="{{url_for('blogger.about')}}">About</a></li>
					<li><a href="{{url_for('blogger.terms_and_conditions')}}">Terms Conditions</a></li>
				</ul>
			</nav>

		<!-- Main -->
			<div id="main">

				<!-- Section -->
					<section class="wrapper">
						<div class="inner">
                            
                        
						
						</div>
					</section>

				
			</div>

		<!-- footer -->
		<footer id="footer">
			<div class="copyright">
				<ul class="icons">
					
					<li><a href="www.facebook.com/ioton" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="www.youtube.com" class="icon fa-youtube"><span class="label">Youtube</span></a></li>
				</ul>
				<p>&copy; 2020. All rights reserved.</p>
			</div>
		</footer>

		<!-- Scripts -->
			<script src="{{url_for('static',filename='assets/js/jquery.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/jquery.scrolly.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/jquery.scrollex.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/skel.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/util.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/main.js')}}"></script>

	</body>
</html>

templates/blogger/Chemistry/Nutrition.html
{% extends 'blogger/template.html' %}
{% block articles %}
<header>
    <h4>Nutrition</h4>
</header>
<p>Nutritional requirement of organisms vary, for humans these requirements are molecules that provide energy and essential elements for surevival. The molecules are broken down into small absorbable bits through digestion.</p>
<p>Digestion is the chemical and mechanical breakdown of large edible organic molecules into smaller absorbable ones. Digestion in Humans starts in the mouth. Ingestd food is chewed and chemically broken down by enzymes into small folds called chyme. Chyme passes throgh the oesophagus by paristalysis into the stomach were temporary storage and further digestion takes place.</p>
<p>In the stomach, HCl pepsin, Renein and other gastro enzymes are released which chages the PH, disinfects the food and breaks down protein. The final product of this vigorous process chime is released into the duodenum of the small intestine</p>
<p></p>
{% endblock %}

templates/blogger/Chemistry/Virus.html
{% extends 'blogger/template.html' %}
{% block articles %}
<header>
    <h4>Virus</h4>
</header>
<p>The smallest form life can ever take is the form of a virus. Viruses are capsules of DNA molecules that oly replicate and perform other life activities in a living cell. They are parasiteic in nature and are only visivle under electron microscope.
Viruses lack cytoplasm, pathologist believe virus have developed such a structue due to their effective acuisistion of nutrients from affected cells.
Up until now, There is no cure for viral infections as the disease live inside cells. But medical prescriptions exist that suppress cell replication in afected cells.
Viruses affect bacteria, plants and every other organisms larger than it. Viruses are of two types REtro virus.</p>

<header>
    <h4>Retro Virus</h4>
</header>
<p>Retro virus contain RNA. when found inside a living tissue, The Rnal undergoes reverse transcription to create DNA. This Dna is then read by the cell to produce more retroviruses. An example of a Retrovirus is HIV. The cause of Aids.</p>
{% endblock%}

templates/blogger/Chemistry/index.html
<!DOCTYPE HTML>

<html>
	<head>
		<title>Ioton</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{{url_for('static',filename='assets/css/main.css')}}" />
	</head>
	<body class="subpage">

		<!-- Header -->
			<header id="header">
				<div class="logo"><a href="{{url_for('blogger.homepage')}}">Io<span>Ton</span></a></div>
				<a href="#menu">Menu</a>
			</header>

		<!-- Nav --> 
			<nav id="menu">
				<ul class="links">
					<li><a href="{{url_for('blogger.homepage')}}">Home</a></li>
					<li><a href="{{url_for('blogger.about')}}">About</a></li>
					<li><a href="{{url_for('blogger.terms_and_conditions')}}">Terms Conditions</a></li>
				</ul>
			</nav>

		<!-- Main -->
			<div id="main">

				<!-- Section -->
					<section class="wrapper">
						<div class="inner">
                            
                        
						
						</div>
					</section>

				
			</div>

		<!-- footer -->
		<footer id="footer">
			<div class="copyright">
				<ul class="icons">
					
					<li><a href="www.facebook.com/ioton" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="www.youtube.com" class="icon fa-youtube"><span class="label">Youtube</span></a></li>
				</ul>
				<p>&copy; 2020. All rights reserved.</p>
			</div>
		</footer>

		<!-- Scripts -->
			<script src="{{url_for('static',filename='assets/js/jquery.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/jquery.scrolly.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/jquery.scrollex.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/skel.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/util.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/main.js')}}"></script>

	</body>
</html>

templates/blogger/Chemistry/respiration.html
{% extends 'blogger/template.html' %}
{% block articles %}




<!-- Article-->
<header>
    <h4>Respiration</h4>
</header>
<p>Every organism respires. Through respiration energy is created which is used by the cells to perform various functions. Respiration in mammals consist of two staes External, and Tissue respiration.</p>
<header>
    <h4>External respiration</h4>
</header>
<p>External respiration, also known as breathing, is the exchange of gases between the environment and the organism. External respiration begins with inhalation of air. The inhaled air passes through these organs sequencially from the nostrils to the pharynx, laynx, trachea, bronchi, bronchioles than finally to the alveolar folds. At the aveolar gaseseous exchange takes place between the blood and air. This occurs in line with concentration gradient.
    Blood and aveolar has a high concentration of carbondioxide and low concentration of oxygen. so oxygen from the inhaled air gets into the blood while carbon diooxide flows out.</p>

    <header>
        <h4>Tissue Respiration</h4>
    </header>
    <p>Tissue respiration is the energy extraction stage of respiration. it occurs in the cells. Oxygen in the blood is used to break down glucose and in the process ATP( Adenosine Triphosphate) an energy carrier is formed.
        Tissue respiration consist of two processes 1. Glycolysis and 2. Kreb Cycle.
        Glycolysis involves the sequencioal break down of glucose into 2 molecules of pyruvate in the cytoplasm. In the process 2 ATP are formed. In the presence of Oxygen, pyruvate is trasferred into mitochondria where it is further transformed to release 36 ATP</p>
<!--
    <header>
    <h4></h4>
</header>
<p></p>
-->



{% endblock %}

templates/blogger/Chemistry/respirtion.html
{% extends 'blogger/template.html' %}
{% block articles %}
<p>
    <dt>Respiration</dt>
    <dd>Every organism respires. Through respiration energy is created which is used by the cells to perform various functions. Respiration in mammals consist of two staes External, and Tissue respiration.</dd>
</p>

<dt>External respiration</dt>
<dd>External respiration, also known as breathing, is the exchange of gases between the environment and the organism. External respiration begins with inhalation of air. The inhaled air passes through these organs sequencially from the nostrils to the pharynx, laynx, trachea, bronchi, bronchioles than finally to the alveolar folds. At the aveolar gaseseous exchange takes place between the blood and air. This occurs in line with concentration gradient.</dd>
<dd>Blood and aveolar has a high concentration of carbondioxide and low concentration of oxygen. so oxygen from the inhaled air gets into the blood while carbon diooxide flows out.</dd>
<dt>Tissue Respiration</dt>
<dd>Tissue respiration is the energy extraction stage of respiration. it occurs in the cells. Oxygen in the blood is used to break down glucose and in the process ATP( Adenosine Triphosphate) an energy carrier is formed.</dd>
<dd>Tissue respiration consist of two processes 1. Glycolysis and 2. Kreb Cycle.</dd>
<dd>Glycolysis involves the sequencioal break down of glucose into 2 molecules of pyruvate in the cytoplasm. In the process 2 ATP are formed. In the presence of Oxygen, pyruvate is trasferred into mitochondria where it is further transformed to release 36 ATP</dd>{% endblock %}

templates/blogger/Programming/index.html
<!DOCTYPE HTML>

<html>
	<head>
		<title>Ioton</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{{url_for('static',filename='assets/css/main.css')}}" />
	</head>
	<body class="subpage">

		<!-- Header -->
			<header id="header">
				<div class="logo"><a href="{{url_for('blogger.homepage')}}">Io<span>Ton</span></a></div>
				<a href="#menu">Menu</a>
			</header>

		<!-- Nav --> 
			<nav id="menu">
				<ul class="links">
					<li><a href="{{url_for('blogger.homepage')}}">Home</a></li>
					<li><a href="{{url_for('blogger.about')}}">About</a></li>
					<li><a href="{{url_for('blogger.terms_and_conditions')}}">Terms Conditions</a></li>
				</ul>
			</nav>

		<!-- Main -->
			<div id="main">

				<!-- Section -->
					<section class="wrapper">
						<div class="inner">
                            
                        
						
						</div>
					</section>

				
			</div>

		<!-- footer -->
		<footer id="footer">
			<div class="copyright">
				<ul class="icons">
					
					<li><a href="www.facebook.com/ioton" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="www.youtube.com" class="icon fa-youtube"><span class="label">Youtube</span></a></li>
				</ul>
				<p>&copy; 2020. All rights reserved.</p>
			</div>
		</footer>

		<!-- Scripts -->
			<script src="{{url_for('static',filename='assets/js/jquery.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/jquery.scrolly.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/jquery.scrollex.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/skel.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/util.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/main.js')}}"></script>

	</body>
</html>

templates/blogger/about.html
{% extends 'blogger/template.html' %}
{% block articles %}
<hr>
<div class="myown">
    <header class="align-center">
        <h1>About Ioton</h4>
    </header>
    <p>Iotonic is a website that offers free tutorial on computer proramming, Biology and Chemistry. It was created in the year 2020 on the 19th of July by Seth Ikiroma-Owiye. Tutorials are prepared with the beginner in mind therefor creativity and simplicity is always searched for while preparing tutorials.</p>
</div>


<hr>

{% endblock %}

templates/blogger/index.html
<!DOCTYPE HTML>

<html>
	<head>
		<title>Ioton</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{{url_for('static',filename='assets/css/main.css')}}" />
	</head>
	<body>

		<!-- Header -->
			<header id="header" class="alt">
				<div class="logo"><a href="{{url_for('blogger.homepage')}}">Io<span>Ton</span></a></div>
				<a href="#menu">Menu</a>
			</header>

		<!-- Nav --> 
		<nav id="menu">
			<ul class="links">
				<li><a href="{{url_for('blogger.homepage')}}">Home</a></li>
				<li><a href="{{url_for('blogger.about')}}">About</a></li>
				<li><a href="{{url_for('blogger.terms_and_conditions')}}">Terms Conditions</a></li>
			</ul>
		</nav>

		<!-- Banner -->
			<section id="banner">
				<div class="inner">
					<header>
						<h1>Keep Learning, Keep Growing</h1>
						<p>Preparation<br />Cross your limitations and pave your way to success</p>
					</header>
					
				</div>
			</section>

		<!-- Main -->
			<div id="main">

				<!-- Section -->
					<section class="wrapper style1">
						<div class="inner">
							<!-- 2 Columns -->
								<div class="flex flex-2">
									<div class="col col1">
										<div class="image round fit">
											<a href="generic.html" class="link"><img src="{{url_for('static',filename='images/fourth.jpg')}}" alt="" /></a>
										</div>
									</div>
									<div class="col col2">
										<h3>Chemistry</h3>
										<p>As tiny as bacteria is, it has been the cause of misery for many multicellular organisms. what makes bacteria so powerful is it's single cell nature. Bacteria can exist as a cell and still perform all life sustaining activities which include reproduction, irritability, excretion, respiration etc.</p>
										<p>Cell is the basic unit of life. like bacteria, every orgaism is made up of cells. these cells individually perform specific activities that keeps the organism alive. The death of an oraganism starts with the death of a cell</p>
										<a href="{{url_for('blogger.chemistry')}}" class="button">Learn More</a>
									</div>
								</div>
						</div>
					</section>

				<!-- Section -->
					<section class="wrapper style2">
						<div class="inner">
							<div class="flex flex-2">
								<div class="col col2">
									<h3>Biology</h3>
									<p>The beauty of nature lies in it's diverse number of inter-dependent creatures that harness it's environment. These creatures tender, walk and maintain balance by changing from time to time the concentration of resources in the environment.</p>
									<p>The sea, air and land depends on these creatures to maintain balance and uniformity. A great effort put by natures of creation to protect nature.</p>
									<a href="{{url_for('blogger.biology')}}" class="button">Learn More</a>
								</div>
								<div class="col col1 first">
									<div class="image round fit">
										<a href="generic.html" class="link"><img src="{{url_for('static',filename='images/third_pic.jpg')}}" alt="" /></a>
									</div>
								</div>
							</div>
						</div>
					</section>

				<!-- Section -->
                <section class="wrapper style1">
                    <div class="inner">
                        <!-- 2 Columns -->
                            <div class="flex flex-2">
                                <div class="col col1">
                                    <div class="image round fit">
                                        <a href="generic.html" class="link"><img src="{{url_for('static',filename='images/fifth.jpg')}}" alt="" /></a>
                                    </div>
                                </div>
                                <div class="col col2">
                                    <h3>Programming</h3>
									<p>The power house of the earth are the plants. plants beautify and purify the world we live in, plants provide shelter for creaeping and climbing creatures, plants control wind speed, plants provide medicine, food and cloth. plants are one of natures natural resource.</p>
									<p>
										The rainforest is home to millions of species. This is possible because of the vast number of plants in the rainforest. plants harness the sun's ray to produces food and energy a life saving process which all animals depend on.
									</p>
                                    <a href="{{url_for('blogger.programming')}}" class="button">Learn More</a>
                                </div>
                            </div>
                    </div>
                </section>

			</div>

		<!-- Footer -->
		<footer id="footer">
			<div class="copyright">
				<ul class="icons">
					
					<li><a href="www.facebook.com/ioton" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
					<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
					<li><a href="www.youtube.com" class="icon fa-youtube"><span class="label">Youtube</span></a></li>
				</ul>
				<p>&copy; 2020. All rights reserved.</p>
			</div>
		</footer>

		<!-- Scripts -->
			<script src="{{url_for('static',filename='assets/js/jquery.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/jquery.scrolly.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/jquery.scrollex.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/skel.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/util.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/main.js')}}"></script>

	</body>
</html>

templates/blogger/template.html
<!DOCTYPE HTML>

<html>
	<head>
		<title>Ioton</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{{url_for('static',filename='assets/css/main.css')}}" />
	</head>
	<body class="subpage">

		<!-- Header -->
			<header id="header">
				<div class="logo"><a href="{{url_for('blogger.homepage')}}">Io<span>Ton</span></a></div>
				<a href="#menu">Menu</a>
			</header>

		<!-- Nav --> 
		<nav id="menu">
			<ul class="links">
				<li><a href="{{url_for('blogger.homepage')}}">Home</a></li>
				<li><a href="{{url_for('blogger.about')}}">About</a></li>
				<li><a href="{{url_for('blogger.terms_and_conditions')}}">Terms Conditions</a></li>
			</ul>
		</nav>

		<!-- Main -->
			<div id="main">

				<!-- Section -->
					<section class="wrapper">
						<div class="inner">
						{% block articles %}generate article with python article generator{% endblock %}
						</div>
					</section>

				

			</div>
			<!-- footer -->
			<footer id="footer">
				<div class="copyright">
					<ul class="icons">
						
						<li><a href="www.facebook.com/ioton" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
						<li><a href="#" class="icon fa-instagram"><span class="label">Instagram</span></a></li>
						<li><a href="www.youtube.com" class="icon fa-youtube"><span class="label">Youtube</span></a></li>
					</ul>
					<p>&copy; 2020. All rights reserved.</p>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="{{url_for('static',filename='assets/js/jquery.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/jquery.scrolly.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/jquery.scrollex.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/skel.min.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/util.js')}}"></script>
			<script src="{{url_for('static',filename='assets/js/main.js')}}"></script>

	</body>
</html>

templates/blogger/terms.html
{% extends 'blogger/template.html' %}
{% block articles %}
<hr>
<header>
    <h4>Terms and conditions</h4>
</header>
<p>Iotonic is a website that offers free tutorial on computer proramming, Biology and Chemistry. It was created in the year 2020 on the 19th of July by Seth Ikiroma-Owiye. Tutorials are prepared with the beginner in mind therefor creativity and simplicity is always searched for while preparing tutorials.</p>
<hr>{% endblock %}